"""Netlist import for update_pcb_from_schematic — runs under KiCad's bundled Python.

KiCad's SWIG bindings expose no netlist reader (checked 9.0.8 and the 10.0
branch), so this reimplements the F8 update from exposed primitives:
FootprintLoad + NETINFO_ITEM + pad.SetNet.  The module level stays
stdlib-only so the repo venv can unit-test the pure functions; pcbnew is
imported inside apply(), which only KiCad's own interpreter can run.

Invoked as: python _netlist_import.py <netlist.xml> <board.kicad_pcb>
            [--lib-dir DIR]... [--delete-stale]
Prints a one-line JSON summary (the UpdatePcbResult shape) as the final
line of stdout; on abort writes to stderr and exits nonzero.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import xml.etree.ElementTree as ET


def parse_netlist(path: str) -> tuple[list[dict], list[dict]]:
    """Parse a kicad-cli XML netlist into (components, nets).

    components: [{ref, value, footprint, path}] — footprint "" when unassigned;
    path is the sheetpath+symbol KIID chain for GUI F8 linkage.
    nets: [{name, nodes: [(ref, pin), ...]}] — the netlist @code is ignored;
    net names are the only identity that survives onto the board.
    """
    # stdlib ET on purpose: the input is generated by kicad-cli into a temp
    # dir moments earlier (never attacker-supplied), and this script runs
    # under KiCad's bundled interpreter where defusedxml cannot be installed.
    root = ET.parse(path).getroot()
    components = []
    for comp in root.findall("./components/comp"):
        sheetpath = comp.find("sheetpath")
        prefix = sheetpath.get("tstamps", "/") if sheetpath is not None else "/"
        tstamps = comp.findtext("tstamps") or ""
        components.append(
            {
                "ref": comp.get("ref") or "",
                "value": comp.findtext("value") or "",
                "footprint": comp.findtext("footprint") or "",
                "path": (prefix.rstrip("/") + "/" + tstamps) if tstamps else "",
            }
        )
    nets = []
    for net in root.findall("./nets/net"):
        name = net.get("name") or ""
        if not name:
            continue
        nodes = [(n.get("ref") or "", n.get("pin") or "") for n in net.findall("node")]
        nets.append({"name": name, "nodes": nodes})
    return components, nets


def resolve_pretty(lib: str, lib_dirs: list[str]) -> str | None:
    """Resolve a footprint library nickname to its .pretty directory.

    A lib dir either IS the .pretty (basename match) or CONTAINS it
    (system footprints dir with many .pretty subdirs).
    """
    want = f"{lib}.pretty"
    for d in lib_dirs:
        if os.path.basename(os.path.normpath(d)) == want:
            return d
        cand = os.path.join(d, want)
        if os.path.isdir(cand):
            return cand
    return None


def grid_slot(k: int, ax: int, ay: int, pitch: int) -> tuple[int, int]:
    """Deterministic cluster slot for the k-th newly added footprint.

    10 columns, fixed pitch, growing downward (+Y) from anchor (ax, ay).
    """
    # ponytail: fixed 10mm pitch, big footprints may overlap in the cluster;
    # courtyard-aware packing if it ever matters
    return ax + (k % 10) * pitch, ay + (k // 10) * pitch


def new_summary() -> dict:
    """Zeroed result schema — must mirror models.UpdatePcbResult exactly."""
    return {
        "status": "ok",
        "added": [],
        "value_updated": [],
        "fpid_changed": [],
        "stale_footprints": [],
        "stale_removed": [],
        "nets_added": 0,
        "nets_removed": 0,
        "pads_bound": 0,
        "orphaned_tracks": 0,
        "orphaned_zones": 0,
        "skipped": [],
        "warnings": [],
    }


def apply(
    netlist_path: str, pcb_path: str, lib_dirs: list[str], delete_stale: bool = False
) -> dict:
    """Apply the netlist to the board and save it. Returns the summary dict."""
    import pcbnew  # pyright: ignore[reportMissingImports] — only KiCad's interpreter has this

    components, nets = parse_netlist(netlist_path)
    summary = new_summary()

    board = pcbnew.LoadBoard(pcb_path) if os.path.exists(pcb_path) else pcbnew.NewBoard(pcb_path)

    # Anchor for the new-footprint cluster: strictly below all existing
    # content (+Y is down), computed before anything is added.
    bbox = board.ComputeBoundingBox(False)
    pitch = pcbnew.FromMM(10)
    if bbox.GetWidth() > 0 or bbox.GetHeight() > 0:
        ax, ay = bbox.GetLeft(), bbox.GetBottom() + pitch
    else:
        ax = ay = pcbnew.FromMM(25.4)

    # --- Components, matched by reference (sorted: deterministic layout) ---
    k = 0
    for comp in sorted(components, key=lambda c: c["ref"]):
        ref, value, fpid = comp["ref"], comp["value"], comp["footprint"]
        existing = board.FindFootprintByReference(ref)

        unchanged = existing is not None and (
            not fpid or existing.GetFPID().GetUniStringLibId() == fpid
        )
        if unchanged:
            if existing.GetValue() != value:
                existing.SetValue(value)
                summary["value_updated"].append(ref)
            continue

        # New footprint needed (fresh add or FPID swap): load it first.
        if ":" not in fpid:
            summary["skipped"].append({"ref": ref, "reason": "no_footprint_assigned"})
            continue
        lib, name = fpid.split(":", 1)
        pretty = resolve_pretty(lib, lib_dirs)
        if pretty is None:
            summary["skipped"].append({"ref": ref, "reason": f"footprint_lib_not_found:{lib}"})
            continue
        fp = pcbnew.FootprintLoad(pretty, name)
        if fp is None:
            summary["skipped"].append({"ref": ref, "reason": f"footprint_not_found:{fpid}"})
            continue

        # FootprintLoad returns a prefix-less FPID; restore the nickname
        # or the saved board loses the "Lib:" half.
        fp.SetFPID(pcbnew.LIB_ID(lib, name))
        fp.SetReference(ref)
        fp.SetValue(value)
        if comp["path"]:
            try:
                fp.SetPath(pcbnew.KIID_PATH(comp["path"]))
            except Exception:
                pass  # GUI F8 linkage only; never worth failing the import

        if existing is None:
            x, y = grid_slot(k, ax, ay, pitch)
            k += 1
            fp.SetPosition(pcbnew.VECTOR2I(x, y))
            board.Add(fp)
            summary["added"].append(ref)
        else:
            # Swap preserving placement. SetLayer would not mirror pads or
            # text; Flip is the only correct way to change sides.
            pos = existing.GetPosition()
            orient = existing.GetOrientation()
            flipped = existing.IsFlipped()
            locked = existing.IsLocked()
            board.Remove(existing)
            fp.SetPosition(pos)
            fp.SetOrientation(orient)
            if flipped:
                fp.Flip(pos, pcbnew.FLIP_DIRECTION_LEFT_RIGHT)
            fp.SetLocked(locked)
            board.Add(fp)
            summary["fpid_changed"].append(ref)

    # --- Nets: add-only. Codes are never renumbered, so existing tracks
    # keep valid nets without any remapping. ---
    for net in nets:
        if board.FindNet(net["name"]) is None:
            board.Add(pcbnew.NETINFO_ITEM(board, net["name"]))
            summary["nets_added"] += 1

    # --- Pads: clear-then-rebind, scoped to netlist-matched footprints.
    # Board-only footprints (mounting holes etc.) are never touched. ---
    netlist_refs = {c["ref"] for c in components}
    for ref in netlist_refs:
        fp = board.FindFootprintByReference(ref)
        if fp is not None:
            for pad in fp.Pads():
                pad.SetNetCode(0)
    for net in nets:
        ni = board.FindNet(net["name"])
        for ref, pin in net["nodes"]:
            fp = board.FindFootprintByReference(ref)
            if fp is None:
                summary["warnings"].append(f"net {net['name']}: {ref}.{pin} not on board")
                continue
            hit = False
            for pad in fp.Pads():
                if pad.GetNumber() == pin:
                    pad.SetNet(ni)  # pointer set; SetNetCode can silently no-op
                    hit = True
            if hit:
                summary["pads_bound"] += 1
            else:
                summary["warnings"].append(f"{ref}: pad {pin} not on footprint (net {net['name']})")

    # --- Items on nets whose name vanished from the schematic -> net 0 ---
    live = {n["name"] for n in nets}
    for item in list(board.Tracks()):
        if item.GetNetCode() > 0 and item.GetNetname() not in live:
            item.SetNetCode(0)
            summary["orphaned_tracks"] += 1
    for zone in list(board.Zones()):
        if zone.GetNetCode() > 0 and zone.GetNetname() not in live:
            zone.SetNetCode(0)
            summary["orphaned_zones"] += 1
    for item in list(board.Drawings()):
        if hasattr(item, "GetNetCode") and item.GetNetCode() > 0:
            if item.GetNetname() not in live:
                item.SetNetCode(0)
                summary["orphaned_tracks"] += 1

    # --- Stale footprints: always reported, removed only on request ---
    for fp in list(board.GetFootprints()):
        ref = fp.GetReference()
        if ref in netlist_refs:
            continue
        summary["stale_footprints"].append(ref)
        if delete_stale and not fp.IsLocked():
            board.Remove(fp)
            summary["stale_removed"].append(ref)

    # --- Prune the net table (after rebind/orphan/stale passes) ---
    before = board.GetNetCount()
    try:
        board.RemoveUnusedNets(None)
    except TypeError:
        board.RemoveUnusedNets()
    summary["nets_removed"] = max(0, before - board.GetNetCount())

    if summary["skipped"]:
        summary["status"] = "incomplete"

    pcbnew.SaveBoard(pcb_path, board)
    return summary


def _ensure_wx_app() -> None:
    """Give wxWidgets an application object before pcbnew can ask for one.

    pcbnew is a GUI library used here without a GUI. Most of its API never
    notices, which is why this script ran for months without one, but anything
    reaching wxStandardPaths::Get() asserts, and on macOS that assert kills the
    process rather than warning:

        ./src/common/stdpbase.cpp(59): assert "traits" failed in Get():
        create wxApp before calling this

    Seen twice on the macOS runner, both times on the --delete-stale run of
    TestUpdatePcbE2E, both times fixed by re-running, which is what made it look
    like flake. It is not: the process exits non-zero, so the caller's
    returncode check is right to fail, and the stderr carries no Python
    traceback because nothing Python raised.

    wx ships inside KiCad's own interpreter, so this adds no dependency
    (measured: wxPython 4.2.2 / wxWidgets 3.2.8 alongside pcbnew 9.0.8).
    redirect=False matters, because the default sends stdout to a GUI window
    and the caller parses stdout for the summary.

    Creating one is skipped where there is no display to open, and that check
    has to come first rather than being left to a try/except. The first version
    of this did leave it to one, on the assumption that a failure would raise
    something catchable. It does not: on a headless Linux runner wxPython exits
    the process with "Unable to access the X Display, is $DISPLAY set
    properly?", which took eight passing E2E tests red. A latent problem became
    a certain one, which is exactly what the guard was supposed to prevent.

    So the ceiling is real and is worth stating plainly: a display-less Linux
    host gets no wxApp and keeps whatever behaviour it had, which is a suite
    that passes today. Windows and macOS, where the assert has actually been
    observed, both have a display whenever a user is running this.
    """
    if sys.platform not in ("win32", "darwin") and not (
        os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY")
    ):
        return
    try:
        import wx  # pyright: ignore[reportMissingImports] — ships with KiCad
    except ImportError:
        return
    try:
        app = wx.App.Get() or wx.App(False)
        # wxPython installs its assert handler through wxApp, so until one
        # exists the raw C++ handler runs. On Windows that is a modal "wxWidgets
        # Debug Alert" dialog on the user's desktop, and this subprocess has
        # nobody to click it: the tool call blocks until the caller's 120s
        # timeout. Route any later assert to the log instead, where it reaches
        # stderr and the caller reports it.
        mode = getattr(wx, "APP_ASSERT_LOG", None)
        if mode is not None and hasattr(app, "SetAssertMode"):
            app.SetAssertMode(mode)
    except Exception as exc:  # noqa: BLE001 - never let this be the thing that fails
        # Only reachable for a wx that raises rather than exiting. The
        # display-less case is handled above, because it does not raise.
        print(f"note: no wxApp ({exc}); pcbnew path lookups may assert", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    _ensure_wx_app()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("netlist")
    ap.add_argument("pcb")
    ap.add_argument("--lib-dir", action="append", default=[])
    ap.add_argument("--delete-stale", action="store_true")
    args = ap.parse_args(argv)
    try:
        summary = apply(args.netlist, args.pcb, args.lib_dir, args.delete_stale)
    except Exception as exc:
        print(f"netlist import failed: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    sys.exit(main())
